server:
  listen: 3000

upstreams:
  backend:
    strategy: round_robin
    servers:
      - host: localhost
        port: 8001
        weight: 1
      - host: localhost
        port: 8002
        weight: 1
      - host: localhost
        port: 8003
        weight: 1
      - host: localhost
        port: 8004
        weight: 1

routes:
  - path: /
    upstream: backend
    match_type: prefix
